USE Test;

CREATE TABLE Customer2
(
    CUST_NO INT(5),
    NAME CHAR(20) NOT NULL,
    ADDRESS VARCHAR(40) NOT NULL,
    DOB DATE,
    ID_CARD_NO INT(13),
    ORDERS INT(5) DEFAULT 0,
    CUST_TYPE CHAR(1),

    PRIMARY KEY(CUST_NO),
    UNIQUE(ID_CARD_NO),
    CHECK(ORDERS >= 0),
    CHECK(CUST_TYPE IN ("A", "B", "C"))
);
