USE Test;

CREATE TABLE Customer1
(
    CUST_NO INT(5) PRIMARY KEY,
    NAME CHAR(20) NOT NULL,
    ADDRESS VARCHAR(40) NOT NULL,
    DOB DATE,
    ID_CARD_NO INT(13),
    ORDERS INT(5) DEFAULT 0 CHECK(ORDERS >= 0),
    CUST_TYPE CHAR(1) CHECK(CUST_TYPE IN ("A", "B", "C"))
);
