CREATE TABLE ABBREVIATION
(
    ABBR_ID CHAR(10),
    PRIMARY KEY (ABBR_ID)
);

CREATE TABLE PAPER
(
    PAPER_ID CHAR(12),
    ABBR_ID CHAR(10),
    PRIMARY KEY (PAPER_ID),
    FOREIGN KEY (ABBR_ID) REFERENCES ABBREVIATION (ABBR_ID)
);
